config/routes.rb
Rails.application.routes.draw do    

  devise_scope :user do
    get "admin/login", :to => "admin/sessions#new"    
  end
  
  devise_for :users, :skip => [:registrations], :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'},:controllers => {:sessions=>"sessions"}

  root 'welcome#index'

  get 'employers' => 'employers#index'

  resources :job_seekers

  get '/get_states' , :to => "admin_base#get_states"
    namespace :admin do
      get '' , :to => "dashboard#index"
      resources :job_seekers
      resources :admins
      resources :states
      resources :countries 
    end
    
end

app/views/admin/admins/_form.html.erb
<%= form_for([:admin,@admin]) do |f| %> 
  
  <div class="new_admin_form">
    <%= f.fields_for :user do |user_form| %>
      
      <div class="field">
        <%= user_form.label :first_name, class: "label_field" %>
        <%= user_form.text_field :first_name , autofocus: true,class: "txt_field"%>
      </div>
      
      <div class="field">
        <%= user_form.label :last_name %>
        <%= user_form.text_field :last_name,class: "txt_field" %>
      </div>

      <div class="field">
        <%= user_form.label :email %>
        <%= user_form.email_field :email,class: "txt_field" %>
      </div>

      <div class="field">
        <%= user_form.label :username %>
        <%= user_form.text_field :username, class: "txt_field" %>
      </div>

      <div class="field">
        <%= user_form.label :password %>
        <%= user_form.password_field :password, autocomplete: "off",class: "txt_field" %>
      </div>

      <div class="field">
        <%= user_form.label :password_confirmation %>
        <%= user_form.password_field :password_confirmation, autocomplete: "off",class: "txt_field" %>
      </div>

      <div class="field">
        <%= user_form.label :phone %>
        <%= user_form.text_field :phone,class: "txt_field" %>
      </div>
    
    <% end %>

    <div class="field">
      <%= f.label :status %>
      <%= f.select :status ,Admin::STATUSES,class: "txt_field" %>
    </div>

    <div class="submit-part">
      <%= f.submit 'Save',class: 'btn btn-primary' %>
    </div>

  </div>
<% end %>

app/views/admin/admins/edit.html.erb
<% content_for(:admin_menu) do %>
  <div class="header">            
    <h1 class="page-title">Admin Users</h1>
  </div>
  <ul class="breadcrumb">
    <li>
      <%= link_to "Home" , admin_path %>
      <span class="divider">/</span>
    </li>
    <li>
      <%= link_to "Admin Users" , admin_admins_path %>
      <span class="divider">/</span>
    </li>
    <li class="active">Edit Admin</li>
  </ul>  
<% end %>
<div class="new_header">
<%= render 'form' %>
</div>

app/views/admin/admins/index.html.erb
<% content_for(:admin_menu) do %>
  <div class="header">            
    <h1 class="page-title">Admin Users</h1>
  </div>
  <ul class="breadcrumb">
    <li>
      <%= link_to "Home" , admin_path %>
      <span class="divider">/</span>
    </li>
    <li class="active">Admin Users</li>
  </ul>  
<% end %>
<div class="btn-toolbar">
    <%= link_to '<i class="icon-plus"></i> New Admin User'.html_safe, new_admin_admin_path , class: "btn btn-primary" %>    
    <button class="btn">Import</button>
    <button class="btn">Export</button>
  <div class="btn-group">    
  </div>
</div>
<div class="well">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Username</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Status</th>
          <th style="width: 26px;"></th>
        </tr>
      </thead>
      <tbody>
        <% @admins.each_with_index do |admin,index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= admin.user.first_name %></td>
            <td><%= admin.user.last_name %></td>
            <td><%= admin.user.username %></td>
            <td><%= admin.user.email %></td>
            <td><%= admin.user.phone %></td>
            <td><%= Admin::STATUSES[admin.status] %></td>            
            <td><%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_admin_admin_path(admin) %></td>
            <td><%= link_to '<i class="icon-remove"></i>'.html_safe, admin_admin_path(admin), method: :delete , data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>                
      </tbody>
    </table>
</div>
<div class="digg_pagination">
  <%= will_paginate @admins, :container => false %>
</div>

app/views/admin/admins/new.html.erb
<% content_for(:admin_menu) do %>
  <div class="header">            
    <h1 class="page-title">Admin Users</h1>
  </div>
  <ul class="breadcrumb">
    <li>
      <%= link_to "Home" , admin_path %>
      <span class="divider">/</span>
    </li>
    <li>
      <%= link_to "Admin Users" , admin_admins_path %>
      <span class="divider">/</span>
    </li>
    <li class="active">New Admin</li>
  </ul>  
<% end %>
<div class="new_header">
	<%= render 'form' %>
</div>

app/views/admin/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @admin.status %>
</p>

<%= link_to 'Edit', edit_admin_admin_path(@admin) %> |
<%= link_to 'Back', admin_admins_path %>