config/routes.rb
Rails.application.routes.draw do    

  devise_scope :user do
    get "admin/login", :to => "admin/sessions#new"    
  end
  
  devise_for :users, :skip => [:registrations], :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'},:controllers => {:sessions=>"sessions"}

  root 'welcome#index'

  get 'employers' => 'employers#index'

  resources :job_seekers

  get '/get_states' , :to => "admin_base#get_states"
    namespace :admin do
      get '' , :to => "dashboard#index"
      resources :job_seekers
      resources :admins
      resources :states
      resources :countries 
    end
    
end

app/models/country.rb
class Country < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, use: [:slugged,:finders]

  has_many :states
	
	validates :name,:code,presence: true
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < AdminBaseController
	before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.paginate(:page => params[:page])
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to admin_countries_url, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        flash[:error] = @country.errors.full_messages.map{|x| "<span>#{x}</span>" }.join('<br/>')
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to admin_countries_url, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        flash[:error] = @country.errors.full_messages.map{|x| "<span>#{x}</span>" }.join('<br/>')
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to admin_countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :code, :slug)
    end
end

app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

app/views/admin/countries/_form.html.erb
<%= form_for([:admin,@country]) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>  
  <div class="actions">
    <%= f.submit 'Save',class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/countries/edit.html.erb
<% content_for(:admin_menu) do %>
  <div class="header">            
    <h1 class="page-title">Edit Country</h1>
  </div>
  <ul class="breadcrumb">
    <li>
      <%= link_to "Home" , admin_path %>
      <span class="divider">/</span>
    </li>
    <li>
      <%= link_to "Countries" , admin_countries_path %>
      <span class="divider">/</span>
    </li>
    <li class="active">Edit Country</li>
  </ul>  
<% end %>
<div class="new_header">
<%= render 'form' %>
</div>

app/views/admin/countries/index.html.erb
<% content_for(:admin_menu) do %>
  <div class="header">            
    <h1 class="page-title">Countries</h1>
  </div>
  <ul class="breadcrumb">
    <li>
      <%= link_to "Home" , admin_path %>
      <span class="divider">/</span>
    </li>
    <li class="active">Countries</li>
  </ul>  
<% end %>
<div class="btn-toolbar">
    <%= link_to '<i class="icon-plus"></i> New Country'.html_safe, new_admin_country_path , class: "btn btn-primary" %>    
    <button class="btn">Import</button>
    <button class="btn">Export</button>
  <div class="btn-group">    
  </div>
</div>
<div class="well">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Code</th>
        <th style="width: 26px;"></th>
      </tr>
    </thead>
    <tbody>
      <% @countries.each_with_index do |country,index| %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= country.name %></td>
          <td><%= country.code %></td>
          <td><%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_admin_country_path(country) %></td>
          <td><%= link_to '<i class="icon-remove"></i>'.html_safe, admin_country_path(country), method: :delete , data: { confirm: 'Are you sure?' } %></td>        
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="digg_pagination">
  <%= will_paginate @countries, :container => false %>
</div>

app/views/admin/countries/new.html.erb
<% content_for(:admin_menu) do %>
  <div class="header">            
    <h1 class="page-title">New Country</h1>
  </div>
  <ul class="breadcrumb">
    <li>
      <%= link_to "Home" , admin_path %>
      <span class="divider">/</span>
    </li>
    <li>
      <%= link_to "Countries" , admin_countries_path %>
      <span class="divider">/</span>
    </li>
    <li class="active">New Country</li>
  </ul>  
<% end %>
<div class="new_header">
	<%= render 'form' %>
</div>

app/views/admin/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @country.code %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @country.slug %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>