config/routes.rb
Rails.application.routes.draw do    

  devise_scope :user do
    get "admin/login", :to => "admin/sessions#new"    
  end
  
  devise_for :users, :skip => [:registrations], :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'},:controllers => {:sessions=>"sessions"}

  root 'welcome#index'

  get 'employers' => 'employers#index'

  resources :job_seekers

  get '/get_states' , :to => "admin_base#get_states"
    namespace :admin do
      get '' , :to => "dashboard#index"
      resources :job_seekers
      resources :admins
      resources :states
      resources :countries 
    end
    
end

app/models/state.rb
class State < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, use: [:slugged,:finders]

  belongs_to :country

  validates :name,:country_id,presence: true 
	
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < AdminBaseController
	before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.paginate(:page => params[:page])
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to admin_states_url, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        flash[:error] = @state.errors.full_messages.map{|x| "<span>#{x}</span>" }.join('<br/>')
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to admin_states_url, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        flash[:error] = @state.errors.full_messages.map{|x| "<span>#{x}</span>" }.join('<br/>')
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to admin_states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :country_id)
    end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for([:admin,@state]) do |f| %>  
<div class="new_admin_form new_admin_states_form">
  <div class="field">
    <%= f.label :country_id %>
    <%= f.select :country_id,Country.all.map{|x| [x.name,x.id]},prompt: 'Select Country' %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Save',class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/admin/states/edit.html.erb
<% content_for(:admin_menu) do %>
  <div class="header">            
    <h1 class="page-title">Edit State</h1>
  </div>
  <ul class="breadcrumb">
    <li>
      <%= link_to "Home" , admin_path %>
      <span class="divider">/</span>
    </li>
    <li>
      <%= link_to "States" , admin_states_path %>
      <span class="divider">/</span>
    </li>
    <li class="active">Edit State</li>
  </ul>  
<% end %>
<div class="new_header">
<%= render 'form' %>
</div>

app/views/admin/states/index.html.erb
<% content_for(:admin_menu) do %>
  <div class="header">            
    <h1 class="page-title">States</h1>
  </div>
  <ul class="breadcrumb">
    <li>
      <%= link_to "Home" , admin_path %>
      <span class="divider">/</span>
    </li>
    <li class="active">States</li>
  </ul>  
<% end %>
<div class="btn-toolbar">
    <%= link_to '<i class="icon-plus"></i> New State'.html_safe, new_admin_state_path , class: "btn btn-primary" %>    
    <button class="btn">Import</button>
    <button class="btn">Export</button>
  <div class="btn-group">    
  </div>
</div>
<div class="well">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Country</th>
        <th style="width: 26px;"></th>
      </tr>
    </thead>
    <tbody>
      <% @states.each_with_index do |state,index| %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= state.name %></td>
          <td><%= state.country.name if state.country_id %></td>
          <td><%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_admin_state_path(state) %></td>
          <td><%= link_to '<i class="icon-remove"></i>'.html_safe, admin_state_path(state), method: :delete , data: { confirm: 'Are you sure?' } %></td>        
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="digg_pagination">
  <%= will_paginate @states, :container => false %>
</div>

app/views/admin/states/new.html.erb
<% content_for(:admin_menu) do %>
  <div class="header">            
    <h1 class="page-title">New State</h1>
  </div>
  <ul class="breadcrumb">
    <li>
      <%= link_to "Home" , admin_path %>
      <span class="divider">/</span>
    </li>
    <li>
      <%= link_to "States" , admin_states_path %>
      <span class="divider">/</span>
    </li>
    <li class="active">New State</li>
  </ul>  
<% end %>
<div class="new_header">
	<%= render 'form' %>
</div>

app/views/admin/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @state.country_id %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>