config/routes.rb
Rails.application.routes.draw do    

  devise_scope :user do
    get "admin/login", :to => "admin/sessions#new"    
  end
  
  devise_for :users, :skip => [:registrations], :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'},:controllers => {:sessions=>"sessions"}

  root 'welcome#index'

  get 'employers' => 'employers#index'

  resources :job_seekers

  get '/get_states' , :to => "admin_base#get_states"
    namespace :admin do
      get '' , :to => "dashboard#index"
      resources :job_seekers
      resources :admins
      resources :states
      resources :countries 
    end
    
end

app/controllers/admin_base_controller.rb
class AdminBaseController < ApplicationController
	layout 'admin'
	before_action :authorize_admin? ,:except=>[:get_states]

	def get_states
		@states = State.where("country_id = ?",params[:country_id]).map{|x| [x.name,x.id] }
		render :json=>@states and return false
	end
end

app/helpers/admin_base_helper.rb
module AdminBaseHelper
end

app/views/admin_base/_admin_dashboard_menu.html.erb
<div class="header">
  <div class="stats">
    <p class="stat"><span class="number"><%= Admin.count %></span>Admins</p>
    <p class="stat"><span class="number"><%= JobSeeker.count %></span>JobSeekers</p>
    <p class="stat"><span class="number"><%= '0' %></span>Employers</p>
  </div>        
  <h1 class="page-title">Dashboard</h1>
</div>
  
<ul class="breadcrumb">
  <li>
    <%= link_to "Home" , admin_path %>
    <span class="divider">/</span>
  </li>
  <li class="active">Dashboard</li>
</ul>

app/views/admin_base/_side_bar.html.erb
<a href="#dashboard-menu" class="nav-header" data-toggle="collapse">
  <i class="icon-dashboard"></i>Dashboard
</a>
<ul id="dashboard-menu" class="nav nav-list collapse in">
  <li><%= link_to "Home", admin_path %></a></li>
  <li><%= link_to "Admin Users", admin_admins_path %></a></li>
  <li><%= link_to "Job Seekers", admin_job_seekers_path %></a></li>
  <li><%= link_to "Employers", "#" %></a></li>
  <li><%= link_to "Jobs Posted", "#" %></a></li>          
</ul>
  
<a href="#accounts-menu" class="nav-header" data-toggle="collapse">
  <i class="icon-briefcase"></i>Account
</a>  
<ul id="accounts-menu" class="nav nav-list collapse">
  <li >
    <%= link_to "View" , admin_admin_path(current_user.accountable) if current_user.present? %>          
  </li>
  <li>
    <%= link_to "Edit" , edit_admin_admin_path(current_user.accountable) if current_user.present? %>          
  </li>
  <li ><a href="#">Reset Password</a></li>
</ul>

<a href="#tools-menu" class="nav-header" data-toggle="collapse"><i class="icon-legal"></i>Tools</a>
<ul id="tools-menu" class="nav nav-list collapse">
  <li><%=link_to "Country" ,admin_countries_path  %></li>
  <li><%=link_to "State" ,admin_states_path %></li>
  <li><%= link_to "Media","#" %></li>  
</ul>
</li>

<a href="#error-menu" class="nav-header collapsed" data-toggle="collapse">
  <i class="icon-exclamation-sign"></i>Error Pages <i class="icon-chevron-up"></i>
</a>
<ul id="error-menu" class="nav nav-list collapse">
  <li ><a href="/404">404 page</a></li>
  <li ><a href="/422">422 page</a></li>
  <li ><a href="/500">500 page</a></li>
  <!-- <li ><a href="503.html">503 page</a></li> -->
</ul>

<a href="#legal-menu" class="nav-header" data-toggle="collapse"><i class="icon-legal"></i>Legal</a>
<ul id="legal-menu" class="nav nav-list collapse">
  <li ><a href="#">Privacy Policy</a></li>
  <li ><a href="#">Terms and Conditions</a></li>
</ul>

<a href="#" class="nav-header"><i class="icon-comment"></i>Faq</a>
<a href="#" class="nav-header" ><i class="icon-question-sign"></i>Help</a>